version: '3'

services:
  
  spa:
    image: johnt1000/vue:1.0
    ports:
      - 8080:8080
    build:
      context: ./spa
    command: npm run serve
    env_file:
      - .env
    volumes:
      - ./spa:/app
      - /app/node_modules
    # depends_on:
    #   - "api"
  
  api:
    image: johnt1000/loopback:1.0
    ports:
      - 3000:3000
    build:
      context: ./api
    command: npm start
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules